version: "3"
services:
  app:
    image: nginx
    container_name: geopaint
    volumes:
      - ./www:/usr/share/nginx/html
    networks:
      - webgis
volumes:
  www:
networks:
  webgis:
    external: true
    